/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OdenLoginRouteImport } from './routes/oden.login'
import { Route as BrowseCategoryIndexRouteImport } from './routes/browse.$category.index'
import { Route as BrowseCategoryTopicDayRouteImport } from './routes/browse.$category.$topic.$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OdenLoginRoute = OdenLoginRouteImport.update({
  id: '/oden/login',
  path: '/oden/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCategoryIndexRoute = BrowseCategoryIndexRouteImport.update({
  id: '/browse/$category/',
  path: '/browse/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCategoryTopicDayRoute = BrowseCategoryTopicDayRouteImport.update({
  id: '/browse/$category/$topic/$day',
  path: '/browse/$category/$topic/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/oden/login': typeof OdenLoginRoute
  '/browse/$category/': typeof BrowseCategoryIndexRoute
  '/browse/$category/$topic/$day': typeof BrowseCategoryTopicDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/oden/login': typeof OdenLoginRoute
  '/browse/$category': typeof BrowseCategoryIndexRoute
  '/browse/$category/$topic/$day': typeof BrowseCategoryTopicDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explorer': typeof ExplorerRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/oden/login': typeof OdenLoginRoute
  '/browse/$category/': typeof BrowseCategoryIndexRoute
  '/browse/$category/$topic/$day': typeof BrowseCategoryTopicDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explorer'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/oden/login'
    | '/browse/$category/'
    | '/browse/$category/$topic/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explorer'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/oden/login'
    | '/browse/$category'
    | '/browse/$category/$topic/$day'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explorer'
    | '/search'
    | '/settings'
    | '/sitemap.xml'
    | '/oden/login'
    | '/browse/$category/'
    | '/browse/$category/$topic/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExplorerRoute: typeof ExplorerRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OdenLoginRoute: typeof OdenLoginRoute
  BrowseCategoryIndexRoute: typeof BrowseCategoryIndexRoute
  BrowseCategoryTopicDayRoute: typeof BrowseCategoryTopicDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oden/login': {
      id: '/oden/login'
      path: '/oden/login'
      fullPath: '/oden/login'
      preLoaderRoute: typeof OdenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$category/': {
      id: '/browse/$category/'
      path: '/browse/$category'
      fullPath: '/browse/$category/'
      preLoaderRoute: typeof BrowseCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$category/$topic/$day': {
      id: '/browse/$category/$topic/$day'
      path: '/browse/$category/$topic/$day'
      fullPath: '/browse/$category/$topic/$day'
      preLoaderRoute: typeof BrowseCategoryTopicDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExplorerRoute: ExplorerRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OdenLoginRoute: OdenLoginRoute,
  BrowseCategoryIndexRoute: BrowseCategoryIndexRoute,
  BrowseCategoryTopicDayRoute: BrowseCategoryTopicDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
